% -------------------------------------------------------------------
%  Generated by MATLAB on 15-May-2017 14:22:34
%  MATLAB version: 9.2.0.538062 (R2017a)
% -------------------------------------------------------------------
                                                

Amp = Simulink.Parameter;
Amp.Value = [0.5 1 1.5 2];
Amp.CoderInfo.StorageClass = 'Auto';
Amp.Description = '';
Amp.DataType = 'auto';
Amp.Min = [];
Amp.Max = [];
Amp.DocUnits = '';

FreqBase = Simulink.Parameter;
FreqBase.Value = 1.4;
FreqBase.CoderInfo.StorageClass = 'Auto';
FreqBase.Description = '';
FreqBase.DataType = 'auto';
FreqBase.Min = [];
FreqBase.Max = [];
FreqBase.DocUnits = '';

FreqCode = Simulink.Parameter;
FreqCode.Value = 0.125;
FreqCode.CoderInfo.StorageClass = 'Auto';
FreqCode.Description = '';
FreqCode.DataType = 'auto';
FreqCode.Min = [];
FreqCode.Max = [];
FreqCode.DocUnits = '';

Phs = Simulink.Parameter;
Phs.Value = [0 0.78539816339744828 1.5707963267948966 2.3561944901923448 ...
             ];
Phs.CoderInfo.StorageClass = 'Auto';
Phs.Description = '';
Phs.DataType = 'auto';
Phs.Min = [];
Phs.Max = [];
Phs.DocUnits = '';

